config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root_path 'home#index'
  root :to => "home#index"

  resources :authors
  resources :books


  #apis routes
  namespace :api do
  #get '/authors/:id' => 'api'
  get '/authors/:id', to: 'authors#authors_books'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	has_and_belongs_to_many :books


	def full_name
		self.first_name + " "+ self.last_name
	end	
end

app/models/book.rb
class Book < ApplicationRecord
	has_and_belongs_to_many :authors
end

app/controllers/api/authors_controller.rb
class Api::AuthorsController < ApplicationController

	def authors_books
		author = Author.find_by(id: params[:id].to_i)
		if author
			render json: {status: true, message: "Author books Details", auth_name: author.full_name,DateofBirth: author.dob, books: author.books }
		else
			render json: {status: true, message:" Author not found" }
		end	
	end	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

	def index
		@authors = Author.all
	end
		
	def new
		@author = Author.new
	end

	def create
		@author = Author.new(author_params)
		@author.save
		redirect_to authors_path
	end

	def edit
		@author = Author.find_by(id: params[:id])
	end

	def update
		@author = Author.find_by(id: params[:id])
		@author.update(author_params)
		redirect_to authors_path
	end

	def destroy
		@author = Author.find_by(id: params[:id])
		@author.destroy
		redirect_to authors_path
	end
	
	private

	def author_params
		params.require(:author).permit(:first_name, :last_name, :dob, book_ids:[])
	end	
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def index
		@books = Book.all
	end
		
	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		@book.save
		redirect_to books_path
	end

	def edit
		@book = Book.find_by(id: params[:id])
	end

	def update
		@book = Book.find_by(id: params[:id])
		@book.update(book_params)
		redirect_to books_path
	end

	def destroy
		@book = Book.find_by(id: params[:id])
		@book.destroy
		redirect_to books_path
	end
	
	private

	def book_params
		params.require(:book).permit(:book_title, author_ids:[])
	end	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index

    end		
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/authors/_form.html.erb
<%#= form_for :author, url:authors_path do |f| %>
<%= form_for @author do |f| %>
  First name: <%= f.text_field :first_name %><br />
  Last name : <%= f.text_field :last_name %><br />
  DateBirth : <%= f.text_field :dob %><br />
  Book Title: <%= f.collection_select :book_ids, Book.order(:book_title), :id, :book_title, {}, {multiple: true} %>

  <%= f.submit %>
<% end %>

app/views/authors/edit.html.erb
<h1> Edit Author Details</h1>
<%= render :partial => 'form'%>

app/views/authors/index.html.erb
<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>DOB</th>
    <th>Actions</th>

  </tr>
  <% @authors.each do |author|%>
  <tr>
    <td><%=author.first_name%></td>
    <td><%=author.last_name%></td>
    <td><%=author.dob%></td>
    <td><%= link_to "Edit", edit_author_path(author) %> | <%= link_to "Delete", author_path(author), data: { method: :delete, confirm: "Are you sure?" } %>
    </td>
  </tr>
  <% end %>
 
</table>


<center><%= link_to "Create New Author", new_author_path%> </center>

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>

app/views/authors/new.html.erb
<%= render :partial => 'form'%>

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  First name: <%= f.text_field :book_title %><br />
  Book Title: <%= f.collection_select :author_ids, Author.order(:first_name), :id, :first_name, {}, {multiple: true} %>
  <%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<h1> Edit Book Details</h1>
<%= render :partial => 'form'%>

app/views/books/index.html.erb
<table>
  <tr>
    <th>Book Title</th>
    <th>Actions</th>

  </tr>
  <% @books.each do |book|%>
  <tr>
    <td><%=book.book_title%></td>
    <td><%= link_to "Edit", edit_book_path(book) %> | <%= link_to "Delete", book_path(book), data: { method: :delete, confirm: "Are you sure?" } %>
    </td>
  </tr>
  <% end %>
</table>

<center><%= link_to "Create New Book", new_book_path%> </center>



<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>

app/views/books/new.html.erb
<%= render :partial => 'form'%>

app/views/home/index.html.erb
<h1>Welcome to Define Labs Assignemnt test!!</h1>

<%= link_to "AuthorList", authors_path%> | <%= link_to "Books List", books_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthorBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>